version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: cex
      POSTGRES_PASSWORD: cex
      POSTGRES_DB: cex
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

  api:
    build: ./api
    container_name: api
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    networks:
      - backend

  engine:
    build: ./engine
    container_name: engine
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
    networks:
      - backend

  websocket:
    build: ./websocket
    container_name: websocket
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
    ports:
      - "8080:8080"
    networks:
      - backend

  db:
    build: ./db
    container_name: db
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_URL: postgres://cex:cex@postgres:5432/cex
      REDIS_URL: redis://redis:6379
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:

